language: node_js
node_js:
- 12.16.2
script:
- npm run test
after_script:
- cat ./coverage/lcov.info | coveralls
deploy:
  provider: heroku
  api_key:
    secure: EDdTf58cYThvGrkt3M5syTdQTjpMb+H3zSabkHGOc2cD3Flg9A91YrbdbINn4Jx4FbZzuwS9scXJz9zLQtM9O2/51aG6dtQ7qder6yqM0BI5IAfMfB4TfttEnXna+cExpnmzqkYH22rs2fkQv97jNedBSqXdVUHyizAxNlgIl69DZupJKfmT3lCdySu4Na53K0gMPdiA/CWCvqdT9+eGGyhG9V9Zs2Y0pmUolwbh544R/rhQmBHue1ml94vEcRzUsjDc9+Rzz3gCEtB/GqK2NwrtiD8x6kMBInFpEpI8SLoe787oFqimO7iZ6ofz85JMyHZ4Ux4xtrNWgUJ+R7tnQIxuONxvz26x/B3n2rkUlaDPG7h/cVphQka4T6AaX67jAwM/9XnhCf/8hySmrEPlVhKptEIIyheVZ/wbZl2NMoKx8i4I/qeMcPl/5LOwsySzP357moMClh4V9qchG86soFsz0jLD2HBGeZW6rIhvxCTGniRXncrNpG43Gz1FAiNRS6hf7pkAcvdH1vSWeb0udfGVU9SiPySw4wO9enc85GicERFicj9/r4hlRsN4p/2J/gE5hfFK2HyZB3kejoKTStIbuL28Ffyn1KUaQ9coviWqlm5HtsRBXKPgrbsc/As/cpIEiTCI0GL7ahxGv8cGeLQYvvHsEIofA/bl3ZOczq4=
  app: cod19Health
  on:
    repo: jmajurel/cod19Health
    branch: develop
notifications:
  email: false
