language: node_js
node_js:
- 12.16.2
script:
- npm run test
after_script:
- cat ./coverage/lcov.info | coveralls
deploy:
  provider: heroku
  api_key:
    secure: VWXv8SEzz9RASIqLFkRIRDyOQ/6PQf52cJqKQc0hlnpRjMmJE58Wx+9bkGglv8wEH/Z4ZrTQO4nldAPIashTsTL8cu7yAwXHLI+S5pda3k8jZ10UkRfeNPzZ+wjsgA89sa8GrsHl9pjZzBGCOU0Oo1qC1xeEN+TF/0jehpfXHqvo1Zr4bQzxKXSs6hN4DglNSPPpFiCEB193JiXJCv60JuulG58oV4jnKcGng9nxq57GJ6KJDrov2bq//7arvEUsL9Bs6cSupiHe/jlfowetpHv/TDbLx0PbN5fI0soizmALLhb0iOqAgwNMTjnUHgVZzhTaAVwOi7mPtq5QuBszaKTsfB9JH4LmvKHGVJDwBEkl2P9sg8/maEk+EBuOWInGK8SqWJGWEaHjrfe6PhCHd3a1reFrvfKTDuWQifXAS6kwOt+TNU0eUjkHYVle7YiKLSOD0ZMpDkiODT9tq47AypMtRxt4V2QW4v2aC2KeB43aM/wXoM37+WCkp78d81tF5BgUAMNRya+5m0JyhlXchnnGxPUd2mpOguIKV/QGfI3OfwV/X+994iKh6ezOWnbgPxs3LOPGaQzUDCoab5uf3MqbMikmTn0o5Qm2GLH5+H357IzdeywSVbHlh4vpCAqfVRyiZY6VqAJjA/7u6QFfUTsJZPu7Vt0AHcZNqzl5Rg0=
  app:
    develop: cod19-health-dev
    master: cod19-health
