language: node_js
node_js:
- 12.16.2
script:
- npm run test
after_script:
- cat ./coverage/lcov.info | coveralls
deploy:
  provider: heroku
  api_key:
    secure: Gja9MRpb8TXGs2VANNltcHsQX51GrJsSFyvbYGyh2RRpWzcci+N4bWXTrcp+81vqSvx2qdmMIKtKDH9u9uS/qcmZ6AY4aqFiAE00Amx66WST8CWOZ+8/i9YuU7Tguq1We5Biips/D5NL9StsZhPuzwe+fnGH50qurXi4pB2vqTR1SEispLg/c3RwjHbxQVs0Ae2UwFk12+Jw4OL0y+d1F1wTKFzOaV0FYu4HtLb1z87xSbwWSzEQRH9NCQi5bLQa03QdkrNSUOYCpKSsN1eNAr8hBqXersIYFnsJz5yO3kDS/GKFBquqno6U4nT420ux5bJV9HpG6YXfkLjMzNC5UvNiDuqqkG7luqu14BSiCO0NN3p1Pfs8lt1IjN6cWYAV/FjkD6S220IWSfPN1V1t5TMCiCdwx3DqOGYIQeP9P7Hk+wFvgFNL2SS/Mg+19Try6SZ961g1Cw/GPX36HHp3u6Z6r4NxeCjleAWMzji5Xxg+IOEkq+49rUl24djtgd27y6JvMIGwfEqbXxO7e+h2Ank33/yPGs9+OCCfwjuvSxR/x85TlVwMhf8IRUUgXkfcy3zpFmhWsDENeIaXkfXzs2X+lGpXSrhLDU2Mij7oISAjy0W5KTD+Fv+Ctc8zF4x0uDF4jNcn6irI/9ArOKmwi+lCESb30b4qjkrH0pUKDSM=
  app:
    develop: cod19-health-dev
    master: cod19-health
notifications:
  email: false
